### ISSUE TITLE
Problema no Match

### ISSUE THREAD

**Issue by chrystianpaulino** [Rocketseat/semana-omnistack-8#3]
Alguém teve este problema no momento do match no mobile?
https://drive.google.com/file/d/1-GaSc8cVd0vRIWnWR8fh1BQPJ-5ds8Y5/view?usp=sharing
Conferi todo meu código e bate certinho com o que tá no Git.

**Comment by viniarruda** [comment]
Qual o erro? Não percebi nada pela imagem

**Comment by wbalbinot** [comment]
> Alguém teve este problema no momento do match no mobile?
> https://drive.google.com/file/d/1-GaSc8cVd0vRIWnWR8fh1BQPJ-5ds8Y5/view?usp=sharing
> Conferi todo meu código e bate certinho com o que tá no Git.

Chystian, **descreva** mais o problema para evidenciar o que você está procurando ajuda. Aparentemente é o caso da imagem não ter ficado redonda, certo? 

Outra coisa, cole o seu código ou referencie algum link para que o pessoal possa analisar :)

Por fim, se o problema não é relacionado ao código da rocketseat, o recomendado não seria postar issues aqui, mas acho que o pessoal vai entender ;)

**Comment by chrystianpaulino** [comment]
O problema é: No momento do Match, deveria aparecer na frente da tela o contanier(matchContainer) com a logo "its a match", o avatar do usuário que deu match, a bio e o botão de fechar. O que acontece, é que no momento do match, este contanier(matchContainer) continua por trás do contanier(cardsContainer) que contém os usuários para dar like/dislike. Então, ele não aparece corretamente como na web: https://drive.google.com/file/d/1-T7dViw-jnSKYJDG1tY7yOZvQ8vvFRd0/view?usp=sharing
O código que estou usando é exatamente igual ao disponibilizado aqui no github, conferi detalhadamente antes de postar aqui, e até mesmo copiei e colei pensando que poderia ter algum problema no meu código.

**Comment by viniarruda** [comment]
Você chegou a usar o `...StyleSheet.absoluteFillObject` ?

**Comment by chrystianpaulino** [comment]
Sim, é o mesmo código

**Comment by tota1099** [comment]
Também estou com o mesmo problema. 

Eu vi o pessoal em um grupo de React ajudando uma pessoa a resolver esse problema.. infelizmente não salvei a publicação, por que não tinha chegado nesta parte ainda ...

**Comment by tota1099** [comment]
Consegui resolver o problema. Assim que possível, irei abrir um pull request para o repositório, mas já adiantando, basicamente fiz isto:

Adicionei zIndex 0 nos botões do container (se não adicionar, os botões ficam superiores ao match).

`buttonsContainer: {
        flexDirection: 'row',
        marginBottom: 30,
        zIndex: 0
    },
`

Adicionei uma função que pega o style do container match automaticamente:

`<View style={[ styles.matchContainer, getStyleMatch()]}>`

E obviamente criei a função para pegar dinamicamente:

`function getStyleMatch(){
        return {
            zIndex: users.length + 1
        }
    }`

Eu poderia ter simplesmente adicionado o zIndex como 999, porém isso seria uma gambiarra.. já que iria trazer problema se o app tivesse mais de 1000 usuários (dificil mas não impossível!).

**Comment by luizaugustoventura** [comment]
> Consegui resolver o problema. Assim que possível, irei abrir um pull request para o repositório, mas já adiantando, basicamente fiz isto:
> 
> Adicionei zIndex 0 nos botões do container (se não adicionar, os botões ficam superiores ao match).
> 
> `buttonsContainer: { flexDirection: 'row', marginBottom: 30, zIndex: 0 }, `
> 
> Adicionei uma função que pega o style do container match automaticamente:
> 
> `<View style={[ styles.matchContainer, getStyleMatch()]}>`
> 
> E obviamente criei a função para pegar dinamicamente:
> 
> `function getStyleMatch(){ return { zIndex: users.length + 1 } }`
> 
> Eu poderia ter simplesmente adicionado o zIndex como 999, porém isso seria uma gambiarra.. já que iria trazer problema se o app tivesse mais de 1000 usuários (dificil mas não impossível!).

Opa, tudo bem? Desculpa entrar na discussão tão tarde. Na época que a OmniStack 8 estava no ar, eu não tinha tempo para fazer, então deixei o PC ligado de madrugada gravando as aulas hahaha. Terminei a implementação recentemente e tive a mesma ideia que você para resolver o problema. Porém, eu fiz a implementação dos cards de outra forma: 

`<View style={[ styles.matchContainer, { zIndex: users.length + 1 } ]}> conteúdo... </View>`

Eu não tinha pensado na implementação que você pensou, até porque eu sou novo com React. Teria alguma diferença em termos de execução ou performance? Poderia a minha implementação dar algum problema? Pergunto isso porque achei sua solução muito criativa.

**Comment by chrystianpaulino** [comment]
problema resolvido
