### ISSUE TITLE
Texto "Acabou" sempre aparece antes da chamada na api

### ISSUE THREAD

**Issue by marcelloguimaraes** [Rocketseat/semana-omnistack-8#4]
Alguém reparou esse comportamento? Acredito que seria mais agradável aparecer apenas depois de dar o like e não haver mais desenvolvedores, mas sempre que a página recarrega aparece o "Acabou :(" antes mesmo de carregar os usuários.
Tentei mexer no código e entender melhor essa parte do Hooks mas nada funcionou, alguém consegue ajudar?

**Comment by emmanuelkant** [comment]
Nesse caso temos que construir um loading component para nos auxiliar. Esse component seria renderizado sempre que front começar a fazer alguma chamada a API. E o texto "acabou :(" só deve ser renderizado seguindo a seguinte condição. 

```javascript
{
   if (!loading && user.length === 0) {
      <div>Acabou : (</div>
   } 
}
```

**Comment by viniarruda** [comment]
Pode criar um hook de loading, e atualizar antes e depois da requisição, assim como o emmanuel comentou

**Comment by marcelloguimaraes** [comment]
@emmanuelkant @viniarruda Acho que funcionou! Show! Obrigado pela dica. Vou abrir um PR.
